import { LANDING_OFFER_IMAGES } from '@/lib/landing-builder-images'

export type HubFunnelStep = {
  num: string
  title: string
  desc: string
}

export type HubOfferCard = {
  name: string
  amount: string
  amountNote: string
  tag: string
  desc: string
  href: string
  cta: string
  imageSrc?: string
  imageAlt?: string
  imagePosition?: string
}

export type HubTabId =
  | 'journey'
  | 'guides'
  | 'find-funds'
  | 'tools'
  | 'inbox'
  | 'organizations'
  | 'refinance'

export type HubTabConfig = {
  brandLine: string
  title: string
  titleAccent?: string
  subtitle: string
  imageSrc: string
  imageAlt: string
  imagePosition: string
  cta?: { href: string; label: string }
  offerTitle: string
  funnelTitle: string
  funnel: HubFunnelStep[]
  funnelCta: { href: string; label: string }
  offers: HubOfferCard[]
}

export const HUB_TAB_CONFIG: Record<HubTabId, HubTabConfig> = {
  journey: {
    brandLine: 'My Journey',
    title: 'Your homebuying',
    titleAccent: 'command center.',
    subtitle: 'Today’s move, your plan, money tools, and guides — one clear path to closing.',
    imageSrc: '/images/builders/nv-family-porch.jpg',
    imageAlt: 'Family on the porch of their new home',
    imagePosition: 'center 48%',
    cta: { href: '/customized-journey?tab=today', label: "See today's move" },
    offerTitle: 'Tools on your journey',
    funnelTitle: 'Three steps to stay on track',
    funnel: [
      { num: '01', title: 'Check today’s move', desc: 'One action surfaced for your current phase.' },
      { num: '02', title: 'Use money tools', desc: 'Savings snapshot, down payment, and fee clarity.' },
      { num: '03', title: 'Close with confidence', desc: 'Scripts and checklists when conversations get tough.' },
    ],
    funnelCta: { href: '/customized-journey?tab=today', label: 'Open your roadmap' },
    offers: [
      {
        name: 'Action inbox',
        amount: 'Today',
        amountNote: 'next best step',
        tag: 'inbox',
        desc: 'Reminders synced with your phase.',
        href: '/inbox',
        cta: 'Open inbox',
        imageSrc: LANDING_OFFER_IMAGES.scripts.src,
        imageAlt: 'Couple planning their move',
        imagePosition: LANDING_OFFER_IMAGES.scripts.position,
      },
      {
        name: 'Find funds',
        amount: '$10k+',
        amountNote: 'program potential',
        tag: 'funds',
        desc: 'Down payment optimizer and grant matching.',
        href: '/down-payment-optimizer',
        cta: 'Find funds',
        imageSrc: LANDING_OFFER_IMAGES.grants.src,
        imageAlt: 'Family with keys to new home',
        imagePosition: LANDING_OFFER_IMAGES.grants.position,
      },
      {
        name: 'Playbooks',
        amount: '24/7',
        amountNote: 'scripts ready',
        tag: 'guides',
        desc: 'Word-for-word prompts for every phase.',
        href: '/resources',
        cta: 'Browse guides',
        imageSrc: LANDING_OFFER_IMAGES.budget.src,
        imageAlt: 'Family in new kitchen',
        imagePosition: LANDING_OFFER_IMAGES.budget.position,
      },
      {
        name: 'Savings snapshot',
        amount: '90 sec',
        amountNote: 'to refresh',
        tag: 'snapshot',
        desc: 'Update your numbers anytime.',
        href: '/results',
        cta: 'View snapshot',
        imageSrc: LANDING_OFFER_IMAGES.fees.src,
        imageAlt: 'New home exterior',
        imagePosition: LANDING_OFFER_IMAGES.fees.position,
      },
    ],
  },
  guides: {
    brandLine: 'Guides',
    title: 'Playbooks for',
    titleAccent: 'every phase.',
    subtitle: 'Scripts, checklists, and short guides — scan fast, act faster.',
    imageSrc: '/images/builders/pulte-family-kitchen.jpg',
    imageAlt: 'Family in their new home kitchen',
    imagePosition: 'center 35%',
    cta: { href: '/customized-journey?tab=library', label: 'Apply in your journey' },
    offerTitle: 'Pair guides with action',
    funnelTitle: 'From reading to doing',
    funnel: [
      { num: '01', title: 'Pick your phase', desc: 'Open the playbook that matches where you are.' },
      { num: '02', title: 'Copy the script', desc: 'Use exact words for lenders, agents, and sellers.' },
      { num: '03', title: 'Mark progress', desc: 'Check off tasks in your Action Roadmap.' },
    ],
    funnelCta: { href: '/customized-journey?tab=plan', label: 'Open roadmap' },
    offers: [
      {
        name: 'Action roadmap',
        amount: '6',
        amountNote: 'phases tracked',
        tag: 'journey',
        desc: 'Turn guides into completed milestones.',
        href: '/customized-journey',
        cta: 'My Journey',
        imageSrc: '/images/builders/nv-couple-steps.jpg',
        imageAlt: 'Couple on new home steps',
        imagePosition: 'center 55%',
      },
      {
        name: 'Find funds',
        amount: '$10k+',
        amountNote: 'programs indexed',
        tag: 'funds',
        desc: 'Match grants to your profile.',
        href: '/down-payment-optimizer',
        cta: 'Find funds',
        imageSrc: LANDING_OFFER_IMAGES.grants.src,
        imageAlt: 'Family celebrating purchase',
        imagePosition: LANDING_OFFER_IMAGES.grants.position,
      },
      {
        name: 'Inbox',
        amount: 'Weekly',
        amountNote: 'reminders',
        tag: 'inbox',
        desc: 'Never miss a deadline before closing.',
        href: '/inbox',
        cta: 'Open inbox',
        imageSrc: '/images/builders/nv-couple-sold.jpg',
        imageAlt: 'Couple at new home',
        imagePosition: 'center 38%',
      },
      {
        name: 'Savings snapshot',
        amount: 'Live',
        amountNote: 'fee clarity',
        tag: 'fees',
        desc: 'See closing costs to question.',
        href: '/results',
        cta: 'View snapshot',
        imageSrc: LANDING_OFFER_IMAGES.fees.src,
        imageAlt: 'Home exterior',
        imagePosition: LANDING_OFFER_IMAGES.fees.position,
      },
    ],
  },
  'find-funds': {
    brandLine: 'Find Funds',
    title: 'Down payment',
    titleAccent: 'optimizer.',
    subtitle: 'See what to save, how long it takes, and which programs may help.',
    imageSrc: '/images/builders/nv-home-exterior.jpg',
    imageAlt: 'Modern new construction home',
    imagePosition: 'center 58%',
    cta: { href: '/quiz?type=first-time', label: 'Match grant programs' },
    offerTitle: 'Stack savings tools',
    funnelTitle: 'Fund your purchase',
    funnel: [
      { num: '01', title: 'Set your target', desc: 'Home price, savings pace, and timeline.' },
      { num: '02', title: 'See the gap', desc: 'FHA, conventional, and program coverage.' },
      { num: '03', title: 'Act in your journey', desc: 'Next steps land in your roadmap and inbox.' },
    ],
    funnelCta: { href: '/customized-journey?tab=today', label: 'Continue journey' },
    offers: [
      {
        name: 'Grant matching',
        amount: '2,000+',
        amountNote: 'programs',
        tag: 'grants',
        desc: 'Full assessment with personalized matches.',
        href: '/quiz?type=first-time',
        cta: 'Start quiz',
        imageSrc: LANDING_OFFER_IMAGES.grants.src,
        imageAlt: 'Family with keys',
        imagePosition: LANDING_OFFER_IMAGES.grants.position,
      },
      {
        name: 'Playbooks',
        amount: 'DPA',
        amountNote: 'how-to guides',
        tag: 'guides',
        desc: 'Scripts for lender conversations.',
        href: '/resources',
        cta: 'Browse guides',
        imageSrc: LANDING_OFFER_IMAGES.scripts.src,
        imageAlt: 'Planning session',
        imagePosition: LANDING_OFFER_IMAGES.scripts.position,
      },
      {
        name: 'Savings snapshot',
        amount: 'Free',
        amountNote: 'affordability check',
        tag: 'budget',
        desc: 'Comfortable payment — not max approval.',
        href: '/results',
        cta: 'View snapshot',
        imageSrc: LANDING_OFFER_IMAGES.budget.src,
        imageAlt: 'Family in kitchen',
        imagePosition: LANDING_OFFER_IMAGES.budget.position,
      },
      {
        name: 'Action inbox',
        amount: 'Sync',
        amountNote: 'with journey',
        tag: 'inbox',
        desc: 'Saving milestones hit your reminders.',
        href: '/inbox',
        cta: 'Open inbox',
        imageSrc: '/images/builders/nv-couple-steps.jpg',
        imageAlt: 'Couple on steps',
        imagePosition: 'center 55%',
      },
    ],
  },
  tools: {
    brandLine: 'Tools & Partners',
    title: 'Closing cost',
    titleAccent: 'marketplace.',
    subtitle: 'Transparent fee comparisons — no commission referrals.',
    imageSrc: '/images/builders/nv-couple-sold.jpg',
    imageAlt: 'Couple in front of their new home',
    imagePosition: 'center 38%',
    cta: { href: '/resources', label: 'Browse guides meanwhile' },
    offerTitle: 'While we onboard providers',
    funnelTitle: 'Prep for closing day',
    funnel: [
      { num: '01', title: 'Audit your fees', desc: 'Use your savings snapshot to spot line items.' },
      { num: '02', title: 'Compare quotes', desc: 'Marketplace launches with vetted providers.' },
      { num: '03', title: 'Negotiate with scripts', desc: 'Playbooks for every fee conversation.' },
    ],
    funnelCta: { href: '/results', label: 'Open savings snapshot' },
    offers: [
      {
        name: 'Fee audit',
        amount: '$3k–$8k',
        amountNote: 'typical savings',
        tag: 'fees',
        desc: 'See which costs to question.',
        href: '/results',
        cta: 'View snapshot',
        imageSrc: LANDING_OFFER_IMAGES.fees.src,
        imageAlt: 'New home',
        imagePosition: LANDING_OFFER_IMAGES.fees.position,
      },
      {
        name: 'Playbooks',
        amount: 'Scripts',
        amountNote: 'for agents & lenders',
        tag: 'guides',
        desc: 'Negotiation prompts ready to copy.',
        href: '/resources',
        cta: 'Browse guides',
        imageSrc: LANDING_OFFER_IMAGES.scripts.src,
        imageAlt: 'Consultation',
        imagePosition: LANDING_OFFER_IMAGES.scripts.position,
      },
      {
        name: 'Find funds',
        amount: 'DPA',
        amountNote: 'programs',
        tag: 'funds',
        desc: 'Reduce cash needed at closing.',
        href: '/down-payment-optimizer',
        cta: 'Find funds',
        imageSrc: LANDING_OFFER_IMAGES.grants.src,
        imageAlt: 'Celebration',
        imagePosition: LANDING_OFFER_IMAGES.grants.position,
      },
      {
        name: 'My Journey',
        amount: 'Track',
        amountNote: 'closing phase',
        tag: 'journey',
        desc: 'Stay on the closing checklist.',
        href: '/customized-journey?tab=plan',
        cta: 'Open roadmap',
        imageSrc: '/images/builders/nv-family-porch.jpg',
        imageAlt: 'Family on porch',
        imagePosition: 'center 48%',
      },
    ],
  },
  inbox: {
    brandLine: 'Inbox',
    title: 'Action',
    titleAccent: 'inbox.',
    subtitle: 'Reminders and next steps — synced with your journey.',
    imageSrc: '/images/builders/nv-couple-steps.jpg',
    imageAlt: 'Couple on the steps of their new home',
    imagePosition: 'center 55%',
    cta: { href: '/customized-journey?tab=today', label: 'Start next action' },
    offerTitle: 'Don’t go it alone',
    funnelTitle: 'Stay ahead of deadlines',
    funnel: [
      { num: '01', title: 'See today’s action', desc: 'One priority surfaced for your phase.' },
      { num: '02', title: 'Snooze or complete', desc: 'Keep your inbox clean and current.' },
      { num: '03', title: 'Use the right script', desc: 'Jump to playbooks when you need words.' },
    ],
    funnelCta: { href: '/resources', label: 'Open playbooks' },
    offers: [
      {
        name: 'Action roadmap',
        amount: 'Live',
        amountNote: 'phase progress',
        tag: 'journey',
        desc: 'Complete tasks from your current phase.',
        href: '/customized-journey?tab=plan',
        cta: 'Open roadmap',
        imageSrc: '/images/builders/nv-family-porch.jpg',
        imageAlt: 'Family at home',
        imagePosition: 'center 48%',
      },
      {
        name: 'Playbooks',
        amount: '24/7',
        amountNote: 'conversation help',
        tag: 'guides',
        desc: 'Scripts for tough conversations.',
        href: '/resources',
        cta: 'Browse guides',
        imageSrc: LANDING_OFFER_IMAGES.scripts.src,
        imageAlt: 'Planning',
        imagePosition: LANDING_OFFER_IMAGES.scripts.position,
      },
      {
        name: 'Find funds',
        amount: 'Programs',
        amountNote: 'matched to you',
        tag: 'funds',
        desc: 'Down payment help before you apply.',
        href: '/down-payment-optimizer',
        cta: 'Find funds',
        imageSrc: LANDING_OFFER_IMAGES.grants.src,
        imageAlt: 'New keys',
        imagePosition: LANDING_OFFER_IMAGES.grants.position,
      },
      {
        name: 'Savings snapshot',
        amount: 'Refresh',
        amountNote: 'your numbers',
        tag: 'snapshot',
        desc: 'Update targets as rates shift.',
        href: '/results',
        cta: 'View snapshot',
        imageSrc: LANDING_OFFER_IMAGES.fees.src,
        imageAlt: 'Home exterior',
        imagePosition: LANDING_OFFER_IMAGES.fees.position,
      },
    ],
  },
  organizations: {
    brandLine: 'For organizations',
    title: 'Homebuyer readiness',
    titleAccent: 'at scale.',
    subtitle: 'Branded assessments and client-ready reports for mission-driven teams.',
    imageSrc: '/images/builders/pulte-couple.jpg',
    imageAlt: 'Team reviewing homebuyer plans',
    imagePosition: 'center 28%',
    cta: { href: '#demo', label: 'Request a demo' },
    offerTitle: 'Built for your mission',
    funnelTitle: 'Launch in weeks, not quarters',
    funnel: [
      { num: '01', title: 'Branded assessment', desc: 'Clients complete a 90-second readiness check.' },
      { num: '02', title: 'Client-ready reports', desc: 'Savings snapshots and exports your team can share.' },
      { num: '03', title: 'Track outcomes', desc: 'Progress data for grants, boards, and compliance.' },
    ],
    funnelCta: { href: '#demo', label: 'Request a demo' },
    offers: [
      {
        name: 'HUD agencies',
        amount: 'Grant',
        amountNote: 'reporting ready',
        tag: 'hud',
        desc: 'Counseling workflows with audit-friendly exports.',
        href: '#demo',
        cta: 'Talk to us',
        imageSrc: '/images/builders/kb-we-see.jpg',
        imageAlt: 'Family outside new home',
        imagePosition: 'center 50%',
      },
      {
        name: 'Credit unions',
        amount: 'Member',
        amountNote: 'first journeys',
        tag: 'cu',
        desc: 'Branded affordability clarity alongside mortgage.',
        href: '#demo',
        cta: 'Talk to us',
        imageSrc: '/images/builders/nv-family-key.jpg',
        imageAlt: 'Family celebration',
        imagePosition: 'center 42%',
      },
      {
        name: 'CDFIs',
        amount: 'Scale',
        amountNote: 'across programs',
        tag: 'cdfi',
        desc: 'Digital readiness across geographies.',
        href: '#demo',
        cta: 'Talk to us',
        imageSrc: '/images/builders/kb-new-beginnings.jpg',
        imageAlt: 'New beginnings',
        imagePosition: 'center 45%',
      },
      {
        name: 'Consumer product',
        amount: 'Free',
        amountNote: 'buyer assessment',
        tag: 'b2c',
        desc: 'See what your clients experience.',
        href: '/',
        cta: 'Try NestQuest',
        imageSrc: LANDING_OFFER_IMAGES.budget.src,
        imageAlt: 'Family in kitchen',
        imagePosition: LANDING_OFFER_IMAGES.budget.position,
      },
    ],
  },
  refinance: {
    brandLine: 'Refinance hub',
    title: 'Optimize your',
    titleAccent: 'home equity.',
    subtitle: 'Monitor rates, cash-out strategies, and smarter refinance decisions.',
    imageSrc: '/images/builders/nv-home-exterior.jpg',
    imageAlt: 'Modern home exterior',
    imagePosition: 'center 58%',
    cta: { href: '/homebuyer/refinance-journey', label: 'Open refinance roadmap' },
    offerTitle: 'Refinance toolkit',
    funnelTitle: 'Three steps to a better rate',
    funnel: [
      { num: '01', title: 'Track your equity', desc: 'Live balance, value, and available equity.' },
      { num: '02', title: 'Set rate alerts', desc: 'Know when market rates beat your current loan.' },
      { num: '03', title: 'Run the analysis', desc: 'Break-even, cash-out, and investment scenarios.' },
    ],
    funnelCta: { href: '/homebuyer/refinance-journey', label: 'Start refinance wizard' },
    offers: [
      {
        name: 'Rate Drop Radar',
        amount: 'Alerts',
        amountNote: 'when rates dip',
        tag: 'rates',
        desc: 'Personalized refinance timing signals.',
        href: '/refinance-optimizer',
        cta: 'Open radar',
        imageSrc: LANDING_OFFER_IMAGES.fees.src,
        imageAlt: 'Home exterior',
        imagePosition: LANDING_OFFER_IMAGES.fees.position,
      },
      {
        name: 'Cash-out optimizer',
        amount: 'Equity',
        amountNote: 'strategies',
        tag: 'cash-out',
        desc: 'Debt consolidation and investment scenarios.',
        href: '/refinance-optimizer',
        cta: 'Explore cash-out',
        imageSrc: '/images/builders/nv-couple-sold.jpg',
        imageAlt: 'Couple at home',
        imagePosition: 'center 38%',
      },
      {
        name: 'Playbooks',
        amount: 'Scripts',
        amountNote: 'for lenders',
        tag: 'guides',
        desc: 'Word-for-word refinance conversations.',
        href: '/resources',
        cta: 'Browse guides',
        imageSrc: LANDING_OFFER_IMAGES.scripts.src,
        imageAlt: 'Planning session',
        imagePosition: LANDING_OFFER_IMAGES.scripts.position,
      },
      {
        name: 'My Journey',
        amount: 'Track',
        amountNote: 'lifecycle health',
        tag: 'journey',
        desc: 'Mortgage lifecycle and progress dashboard.',
        href: '/customized-journey',
        cta: 'Open journey',
        imageSrc: '/images/builders/nv-family-porch.jpg',
        imageAlt: 'Family on porch',
        imagePosition: 'center 48%',
      },
    ],
  },
}
