/** Curated library entries for the journey Library tab (links into /resources). */

import type { UserTier } from './tiers'

export type LibraryCategoryId =
  | 'scripts'
  | 'checklists'
  | 'guides'
  | 'money_finder'
  | 'savings_strategies'
  | 'alternative_solutions'

export type JourneyLibraryItem = {
  id: string
  title: string
  summary: string
  readMin: number
  category: LibraryCategoryId
  href: string
  minTier?: UserTier
}

export const JOURNEY_LIBRARY_ITEMS: JourneyLibraryItem[] = [
  {
    id: 'offer-script',
    title: 'Balanced offer talking points',
    summary: 'Phrases to stay firm on price while sounding collaborative.',
    readMin: 3,
    category: 'scripts',
    href: '/resources#resource-offer-script',
    minTier: 'momentum',
  },
  {
    id: 'inspection-checklist',
    title: 'Inspection day checklist',
    summary: 'Room-by-room signals worth noting before you waive or negotiate.',
    readMin: 5,
    category: 'checklists',
    href: '/resources#resource-inspection-guide',
  },
  {
    id: 'credit-score-guide',
    title: 'Credit score & your mortgage rate',
    summary: 'How scores affect rate tiers and quick wins before you apply.',
    readMin: 7,
    category: 'guides',
    href: '/resources#resource-credit-score-guide',
  },
  {
    id: 'closing-costs-guide',
    title: 'Closing costs in plain English',
    summary: 'Which fees move, which rarely do, and what to compare across lenders.',
    readMin: 8,
    category: 'guides',
    href: '/resources#resource-closing-cost-guide',
  },
  {
    id: 'lender-shop-script',
    title: 'Shopping three lenders (14-day window)',
    summary: 'How to ask for LE apples-to-apples without sounding confrontational.',
    readMin: 4,
    category: 'scripts',
    href: '/resources#resource-negotiation-script-lender',
    minTier: 'momentum',
  },
  {
    id: 'walkthrough-checklist',
    title: 'Final walk-through checklist',
    summary: 'Confirm repairs, appliances, and utilities before signing.',
    readMin: 4,
    category: 'checklists',
    href: '/resources#resource-closing-day-checklist',
  },
  {
    id: 'dti-deep-dive',
    title: 'DTI: front-end vs back-end',
    summary: 'How lenders weigh housing vs total debt — and why your sketch matters.',
    readMin: 7,
    category: 'guides',
    href: '/resources#resource-dti-deep-dive',
  },
  {
    id: 'wire-fraud-safety',
    title: 'Wire instructions verification script',
    summary: 'A short call script to confirm wiring details on a known number.',
    readMin: 2,
    category: 'scripts',
    href: '/resources#resource-closing-script',
    minTier: 'momentum',
  },
  {
    id: 'docs-starter-pack',
    title: 'Lender document starter list',
    summary: 'The core paperwork bundle most buyers gather in early phases.',
    readMin: 5,
    category: 'checklists',
    href: '/resources#resource-doc-checklist',
  },
  {
    id: 'dpa-match',
    title: 'Down payment assistance matcher (checklist)',
    summary: 'Eligibility signals by geography, income band, and first-time status.',
    readMin: 6,
    category: 'money_finder',
    href: '/down-payment-optimizer',
  },
  {
    id: 'state-programs',
    title: 'State & local homebuyer credits',
    summary: 'Where to look for bond programs and siloed municipal funds.',
    readMin: 7,
    category: 'money_finder',
    href: '/down-payment-optimizer',
    minTier: 'momentum',
  },
  {
    id: 'lender-credit-tradeoff',
    title: 'Lender credits vs. rate — break-even math',
    summary: 'When a slightly higher rate pays for closing help you need now.',
    readMin: 6,
    category: 'savings_strategies',
    href: '/resources#resource-lender-credit-tradeoff',
  },
  {
    id: 'pmi-optimization',
    title: 'PMI optimization playbook',
    summary: 'Down payment tiers that drop PMI sooner or shrink the monthly line.',
    readMin: 8,
    category: 'savings_strategies',
    href: '/resources#resource-pmi-optimization',
  },
  {
    id: 'fee-negotiation',
    title: 'Negotiating lender & title fees',
    summary: 'Which line items have flex and how to ask without blowing up the deal.',
    readMin: 5,
    category: 'savings_strategies',
    href: '/resources#resource-negotiation-script-lender',
    minTier: 'navigator',
  },
  {
    id: 'fha-guide',
    title: 'FHA loans explained',
    summary: '3.5% down, MIP, and who FHA fits best.',
    readMin: 8,
    category: 'guides',
    href: '/resources#resource-fha-guide',
  },
  {
    id: 'va-guide',
    title: 'VA loans explained',
    summary: 'Zero down, funding fee, and eligibility basics.',
    readMin: 8,
    category: 'guides',
    href: '/resources#resource-va-guide',
  },
  {
    id: 'usda-guide',
    title: 'USDA rural loans',
    summary: 'Zero down in eligible areas with income limits.',
    readMin: 8,
    category: 'guides',
    href: '/resources#resource-usda-guide',
  },
  {
    id: 'loan-program-comparison',
    title: 'FHA vs conventional vs VA vs USDA',
    summary: 'Side-by-side comparison and self-check questions.',
    readMin: 10,
    category: 'guides',
    href: '/resources#resource-loan-program-comparison',
  },
  {
    id: 'search-without-burnout',
    title: 'Search without burning out',
    summary: 'Must-haves, pacing, and comp research.',
    readMin: 5,
    category: 'guides',
    href: '/resources#resource-search-without-burnout',
  },
  {
    id: 'listing-red-flags',
    title: 'Listing red flags',
    summary: 'Price history, photos, and disclosure gaps.',
    readMin: 5,
    category: 'guides',
    href: '/resources#resource-listing-red-flags',
  },
  {
    id: 'neighborhood-checklist',
    title: 'Neighborhood checklist',
    summary: 'Commute, schools, flood risk before you offer.',
    readMin: 6,
    category: 'checklists',
    href: '/resources#resource-neighborhood-checklist',
  },
  {
    id: 'escrow-explained',
    title: 'Escrow accounts explained',
    summary: 'Taxes, insurance, and payment surprises.',
    readMin: 6,
    category: 'guides',
    href: '/resources#resource-escrow-accounts-explained',
  },
  {
    id: 'title-insurance',
    title: 'Title insurance explained',
    summary: 'Owner vs lender policy and shopping Section C.',
    readMin: 6,
    category: 'guides',
    href: '/resources#resource-title-insurance-explained',
  },
  {
    id: 'closing-day-checklist',
    title: 'Closing day checklist',
    summary: 'What to bring and wire fraud reminder.',
    readMin: 4,
    category: 'checklists',
    href: '/resources#resource-closing-day-checklist',
  },
  {
    id: 'first-year-maintenance',
    title: 'First-year maintenance budget',
    summary: '1–3% rule and seasonal basics.',
    readMin: 6,
    category: 'guides',
    href: '/resources#resource-first-year-maintenance-budget',
  },
  {
    id: 'homeowner-scams',
    title: 'Homeowner scams & help',
    summary: 'Red flags and HUD counselor links.',
    readMin: 5,
    category: 'guides',
    href: '/resources#resource-homeowner-scams-and-help',
  },
  {
    id: 'fair-housing-guide',
    title: 'Fair housing rights',
    summary: 'Protected classes and how to file a complaint.',
    readMin: 7,
    category: 'guides',
    href: '/resources#resource-fair-housing-guide',
  },
  {
    id: 'arm-scenarios',
    title: 'ARM scenarios with exit plans',
    summary: 'Fixed periods, caps, and when ARM beats fixed for 3–7 year holds.',
    readMin: 9,
    category: 'alternative_solutions',
    href: '/resources#resource-arm-scenarios',
    minTier: 'momentum',
  },
  {
    id: 'buydown-structures',
    title: 'Permanent vs temporary buydowns',
    summary: 'Seller concessions, upfront costs, and how payments step down.',
    readMin: 7,
    category: 'alternative_solutions',
    href: '/resources#resource-buydown-structures',
    minTier: 'momentum',
  },
  {
    id: 'reno-loan-primer',
    title: 'Renovation loan primer',
    summary: 'Rolling repairs into purchase when appraisal and contractor scope align.',
    readMin: 8,
    category: 'alternative_solutions',
    href: '/resources#resource-reno-loan-primer',
    minTier: 'navigator',
  },
  {
    id: 'heloc-vs-refi',
    title: 'HELOC vs cash-out refi',
    summary: 'When to tap equity with a line of credit vs replacing your mortgage.',
    readMin: 7,
    category: 'alternative_solutions',
    href: '/resources#resource-heloc-vs-refi',
  },
  {
    id: 'homeowners-insurance-primer',
    title: 'Insurance before closing',
    summary: 'Bind homeowners coverage early — lenders need proof before funding.',
    readMin: 5,
    category: 'guides',
    href: '/resources#resource-homeowners-insurance-primer',
  },
  {
    id: 'choose-buyers-agent',
    title: "How to choose a buyer's agent",
    summary: 'Interview questions and red flags before you commit.',
    readMin: 6,
    category: 'guides',
    href: '/resources#resource-choose-buyers-agent',
  },
  {
    id: 'first-time-mistakes',
    title: '10 first-time buyer mistakes',
    summary: 'Common missteps and what to do instead.',
    readMin: 5,
    category: 'guides',
    href: '/resources#resource-first-time-mistakes',
  },
]

export const JOURNEY_LIBRARY_CATEGORY_LABEL: Record<LibraryCategoryId, string> = {
  scripts: 'Scripts',
  checklists: 'Checklists',
  guides: 'Deep Guides',
  money_finder: 'Money Finder',
  savings_strategies: 'Savings Strategies',
  alternative_solutions: 'Alternative Solutions',
}
